DROP DATABASE IF EXISTS petservice;
DROP USER IF EXISTS `pet_service`@`%`;
CREATE DATABASE IF NOT EXISTS petservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `pet_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `petservice`.* TO `pet_service`@`%`;
FLUSH PRIVILEGES;

